import numpy as np
a1=np.array([1,2,3,4,5,6,7,8,9])
print (a1)
rsa=a1.reshape(3,3)
print (rsa)
print ("accessing")
print (rsa[2][1])
print (rsa[0:2])
print(rsa[:,2])
sum=np.sum(rsa)
print(sum)
sumc=np.sum(rsa,axis=0)
print(sumc)
sumr=np.sum(rsa,axis=1)
print(sumr)
a=np.array([1,2,3])
print(a + 2)
print(a * 3)
